"""empty message

Revision ID: b43cd00508ac
Revises: fa78a07a8cf7
Create Date: 2020-11-08 22:40:33.552342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43cd00508ac'
down_revision = 'fa78a07a8cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
