"""empty message

Revision ID: c93099566e2e
Revises: e2188fcb20b9
Create Date: 2020-11-08 22:17:17.370410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93099566e2e'
down_revision = 'e2188fcb20b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actors_movie_id_fkey', 'actors', type_='foreignkey')
    op.create_foreign_key(None, 'actors', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.create_foreign_key('actors_movie_id_fkey', 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
